name: gptparty_frontend
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_graph_view: ^0.3.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+5
  http: ^0.13.6
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  http_parser: ^4.0.2
  path_provider: ^2.0.15
  get_it: ^7.6.0
  logger: ^1.3.0
  connectivity_plus: ^4.0.0
  mobx: ^2.2.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.3.0
  font_awesome_flutter: ^10.4.0
  flutter_mobx: ^2.0.6+5


  flutter_localizations:
    sdk: flutter
  graphview: ^1.2.0
  enum_to_string: ^2.0.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  # fonts:
  #   - family: Outfit
  #     fonts:
  #       - asset: assets/fonts/Outfit-VariableFont_wght.tff
  uses-material-design: true


  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/data/
